import type { JSX } from "react";
import { useCallback, useState } from "react";
import { X } from "lucide-react";
import EChart from "./EChart";
import ChartCard, { type Provenance } from "./ChartCard";
import KpiCard from "./KpiCard";
import {
  axisLabel,
  grid,
  legend,
  lineStyle,
  motion,
  splitLine,
  tooltip,
  usd,
  withAlpha,
  type VizMode,
  type VizTokens,
} from "./theme";
import raw from "../../data/viz/telecom.json";

/**
 * Telecom revenue & usage dashboard over the documented scenario generated by
 * scripts/generate_viz_data.py (pricing, ARPU and churn rules identical to the
 * project's dbt models). One market filter — a <select> or a click on the
 * market chart — scopes every KPI and chart; colors follow the entity.
 */

interface Monthly { month: string; revenue: number; activeCallers: number; arpu: number; events: number }
interface Scope {
  subscribers: number;
  churned: number;
  events: number;
  roamingShare: number;
  revenue: number;
  arpuMonthlyMean: number;
  monthly: Monthly[];
  revenueByType: Record<"VOICE" | "SMS" | "DATA", number>;
  countByType: Record<"VOICE" | "SMS" | "DATA", number>;
  heatmap: number[][];
  churnRiskByPlan: Record<string, { high: number; medium: number; low: number }>;
}
const data = raw as unknown as {
  _meta: { note: string; assumptions: string[] };
  markets: string[];
  plans: string[];
  months: string[];
  scopes: Record<string, Scope>;
};

const PROV: Provenance = {
  label: "Scenario data · seed 42",
  title: `${data._meta.note} ${data._meta.assumptions.join(" ")}`,
  kind: "synthetic",
};
const TYPES = ["DATA", "VOICE", "SMS"] as const;
const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const monthLabel = (m: string) =>
  new Date(`${m}-01T00:00:00Z`).toLocaleDateString("en-US", { month: "short", year: "2-digit", timeZone: "UTC" });
const pct = (n: number, d = 0) => `${(n * 100).toFixed(d)}%`;

export default function TelecomDashboard(): JSX.Element {
  const [market, setMarket] = useState<string>("ALL");
  const [announce, setAnnounce] = useState("");
  const s = data.scopes[market];
  const all = data.scopes.ALL;

  const choose = useCallback((m: string) => {
    setMarket((cur) => {
      const next = cur === m ? "ALL" : m;
      setAnnounce(next === "ALL" ? "Showing all markets" : `Filtered to ${next}`);
      return next;
    });
  }, []);

  const last = s.monthly[s.monthly.length - 1];
  const first = s.monthly[0];
  const scopeLabel = market === "ALL" ? "all markets" : market;

  // --- option builders (memoised on scope) ------------------------------
  const revenueByMonth = useCallback(
    (t: VizTokens, _m: VizMode, reduced: boolean) => {
      const peak = s.monthly.reduce((a, b) => (b.revenue > a.revenue ? b : a));
      return {
        ...motion(reduced),
        grid: grid({ top: 16 }),
        tooltip: tooltip(t, { trigger: "axis", axisPointer: { type: "shadow" }, valueFormatter: (v: unknown) => usd(Number(v)) }),
        xAxis: { type: "category", data: s.monthly.map((r) => monthLabel(r.month)), axisLabel: axisLabel(t), axisTick: { show: false }, axisLine: { lineStyle: { color: t.border } } },
        yAxis: { type: "value", axisLabel: axisLabel(t, { formatter: (v: number) => usd(v) }), splitLine: splitLine(t) },
        series: [{
          name: "Usage revenue",
          type: "bar",
          data: s.monthly.map((r) => ({
            value: Math.round(r.revenue),
            itemStyle: { color: r.month === peak.month ? t.series[0] : withAlpha(t.series[0], 0.55), borderRadius: [4, 4, 0, 0] },
          })),
          barMaxWidth: 24,
        }],
      };
    },
    [s],
  );

  const arpuByMonth = useCallback(
    (t: VizTokens, _m: VizMode, reduced: boolean) => ({
      ...motion(reduced),
      grid: grid({ top: 16, right: 24 }),
      tooltip: tooltip(t, { trigger: "axis", valueFormatter: (v: unknown) => `$${Number(v).toFixed(2)}` }),
      xAxis: { type: "category", data: s.monthly.map((r) => monthLabel(r.month)), boundaryGap: false, axisLabel: axisLabel(t), axisLine: { lineStyle: { color: t.border } } },
      yAxis: { type: "value", scale: true, axisLabel: axisLabel(t, { formatter: (v: number) => `$${v.toFixed(0)}` }), splitLine: splitLine(t) },
      series: [{
        name: "ARPU per active caller",
        type: "line",
        data: s.monthly.map((r) => +r.arpu.toFixed(2)),
        ...lineStyle(t, t.series[0], true),
        markLine: {
          symbol: "none",
          silent: true,
          label: { color: t.muted, fontSize: 10, formatter: "12-mo mean" },
          lineStyle: { color: t.muted, type: "dashed", width: 1 },
          data: [{ yAxis: +s.arpuMonthlyMean.toFixed(2) }],
        },
      }],
    }),
    [s],
  );

  const byMarket = useCallback(
    (t: VizTokens, _m: VizMode, reduced: boolean) => {
      const rows = [...data.markets].map((m) => ({ m, v: data.scopes[m].revenue })).sort((a, b) => a.v - b.v);
      return {
        ...motion(reduced),
        grid: grid({ top: 8, right: 56 }),
        tooltip: tooltip(t, { trigger: "item", valueFormatter: (v: unknown) => usd(Number(v)) }),
        xAxis: { type: "value", axisLabel: axisLabel(t, { formatter: (v: number) => usd(v) }), splitLine: splitLine(t) },
        yAxis: { type: "category", data: rows.map((r) => r.m), axisLabel: axisLabel(t, { color: t.fg }), axisTick: { show: false }, axisLine: { show: false } },
        series: [{
          type: "bar",
          name: "Revenue",
          barMaxWidth: 22,
          cursor: "pointer",
          data: rows.map((r) => ({
            value: Math.round(r.v),
            itemStyle: {
              color: market === "ALL" || market === r.m ? t.series[0] : withAlpha(t.series[0], 0.22),
              borderRadius: [0, 4, 4, 0],
            },
          })),
          label: { show: true, position: "right", color: t.muted, fontSize: 11, formatter: (p: { value: number }) => usd(p.value) },
        }],
      };
    },
    [market],
  );

  const mix = useCallback(
    (t: VizTokens, _m: VizMode, reduced: boolean) => {
      const evTotal = TYPES.reduce((a, k) => a + s.countByType[k], 0);
      const revTotal = TYPES.reduce((a, k) => a + s.revenueByType[k], 0);
      return {
        ...motion(reduced),
        grid: grid({ top: 36, right: 16 }),
        legend: legend(t, { top: 0, left: 0 }),
        tooltip: tooltip(t, { trigger: "axis", axisPointer: { type: "shadow" }, valueFormatter: (v: unknown) => `${Number(v).toFixed(1)}%` }),
        xAxis: { type: "value", max: 100, axisLabel: axisLabel(t, { formatter: "{value}%" }), splitLine: splitLine(t) },
        yAxis: { type: "category", data: ["Share of revenue", "Share of events"], axisLabel: axisLabel(t, { color: t.fg }), axisTick: { show: false }, axisLine: { show: false } },
        series: TYPES.map((k, i) => ({
          name: k === "SMS" ? "SMS" : k.charAt(0) + k.slice(1).toLowerCase(),
          type: "bar",
          stack: "mix",
          barMaxWidth: 26,
          itemStyle: { color: t.series[i], borderColor: t.surface, borderWidth: 2 },
          emphasis: { focus: "series" },
          data: [+(100 * s.revenueByType[k] / revTotal).toFixed(1), +(100 * s.countByType[k] / evTotal).toFixed(1)],
        })),
      };
    },
    [s],
  );

  const heat = useCallback(
    (t: VizTokens, _m: VizMode, reduced: boolean) => {
      const cells: [number, number, number][] = [];
      s.heatmap.forEach((row, d) => row.forEach((v, h) => cells.push([h, d, v])));
      const max = Math.max(...cells.map((c) => c[2]));
      return {
        ...motion(reduced),
        grid: grid({ top: 8, bottom: 44, left: 8 }),
        tooltip: tooltip(t, {
          trigger: "item",
          formatter: (p: { value: [number, number, number] }) =>
            `<b>${p.value[2].toLocaleString("en-US")}</b> events<br/><span style="opacity:.7">${DAYS[p.value[1]]} ${String(p.value[0]).padStart(2, "0")}:00</span>`,
        }),
        xAxis: { type: "category", data: Array.from({ length: 24 }, (_, h) => String(h).padStart(2, "0")), axisLabel: axisLabel(t, { interval: 2 }), axisTick: { show: false }, axisLine: { show: false }, splitArea: { show: false } },
        yAxis: { type: "category", data: DAYS, inverse: true, axisLabel: axisLabel(t, { color: t.fg }), axisTick: { show: false }, axisLine: { show: false } },
        visualMap: {
          min: 0,
          max,
          calculable: false,
          orient: "horizontal",
          left: "center",
          bottom: 0,
          itemWidth: 10,
          itemHeight: 120,
          text: ["busier", "quieter"],
          textStyle: { color: t.muted, fontSize: 10 },
          inRange: { color: [withAlpha(t.series[0], 0.06), t.series[0]] },
        },
        series: [{ type: "heatmap", data: cells, itemStyle: { borderColor: t.surface, borderWidth: 2, borderRadius: 3 }, emphasis: { itemStyle: { borderColor: t.fg, borderWidth: 1 } } }],
      };
    },
    [s],
  );

  const churn = useCallback(
    (t: VizTokens, _m: VizMode, reduced: boolean) => {
      const plans = [...data.plans].reverse();
      const tiers = [
        { k: "high" as const, name: "High risk", color: t.danger },
        { k: "medium" as const, name: "Medium", color: t.warn },
        { k: "low" as const, name: "Low", color: withAlpha(t.success, 0.75) },
      ];
      return {
        ...motion(reduced),
        grid: grid({ top: 36 }),
        legend: legend(t, { top: 0, left: 0 }),
        tooltip: tooltip(t, { trigger: "axis", axisPointer: { type: "shadow" } }),
        xAxis: { type: "value", axisLabel: axisLabel(t), splitLine: splitLine(t) },
        yAxis: { type: "category", data: plans.map((p) => p.replace(/_/g, " ")), axisLabel: axisLabel(t, { color: t.fg }), axisTick: { show: false }, axisLine: { show: false } },
        series: tiers.map((tier, i) => ({
          name: tier.name,
          type: "bar",
          stack: "risk",
          barMaxWidth: 22,
          itemStyle: { color: tier.color, borderColor: t.surface, borderWidth: 2, borderRadius: i === tiers.length - 1 ? [0, 4, 4, 0] : 0 },
          emphasis: { focus: "series" },
          data: plans.map((p) => s.churnRiskByPlan[p][tier.k]),
        })),
      };
    },
    [s],
  );

  // --- derived numbers for takeaways --------------------------------------
  const peak = s.monthly.reduce((a, b) => (b.revenue > a.revenue ? b : a));
  const revTotal = TYPES.reduce((a, k) => a + s.revenueByType[k], 0);
  const evTotal = TYPES.reduce((a, k) => a + s.countByType[k], 0);
  const dataRevShare = s.revenueByType.DATA / revTotal;
  const dataEvShare = s.countByType.DATA / evTotal;
  const hourTotals = Array.from({ length: 24 }, (_, h) => s.heatmap.reduce((a, row) => a + row[h], 0));
  const busyHour = hourTotals.indexOf(Math.max(...hourTotals));
  const quietHour = hourTotals.indexOf(Math.min(...hourTotals));
  const dayTotals = s.heatmap.map((row) => row.reduce((a, b) => a + b, 0));
  const sunVsWk = dayTotals[6] / (dayTotals.slice(0, 5).reduce((a, b) => a + b, 0) / 5);
  const risk = Object.values(s.churnRiskByPlan).reduce(
    (a, r) => ({ high: a.high + r.high, medium: a.medium + r.medium, low: a.low + r.low }),
    { high: 0, medium: 0, low: 0 },
  );
  const prepaid = s.churnRiskByPlan.PREPAID;
  const prepaidHigh = prepaid.high / Math.max(1, prepaid.high + prepaid.medium + prepaid.low);
  const marketRank = [...data.markets].sort((a, b) => data.scopes[b].revenue - data.scopes[a].revenue);
  const perHead = (m: string) => data.scopes[m].revenue / data.scopes[m].subscribers;
  const perHeadRank = [...data.markets].sort((a, b) => perHead(b) - perHead(a));

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center gap-3">
        <label className="flex items-center gap-2 text-sm">
          <span className="font-mono text-[11px] uppercase tracking-[0.12em] text-muted">Market</span>
          <select
            value={market}
            onChange={(e) => {
              setMarket(e.target.value);
              setAnnounce(e.target.value === "ALL" ? "Showing all markets" : `Filtered to ${e.target.value}`);
            }}
            className="h-9 rounded-lg border border-border bg-surface px-3 text-sm text-fg shadow-1"
          >
            <option value="ALL">All markets</option>
            {data.markets.map((m) => <option key={m} value={m}>{m}</option>)}
          </select>
        </label>
        {market !== "ALL" && (
          <button type="button" className="chip-toggle" aria-pressed="true" onClick={() => choose(market)}>
            {market} <X size={12} aria-hidden="true" /> <span className="sr-only">clear filter</span>
          </button>
        )}
        <p className="text-xs text-muted">Tip: click a bar in “Revenue by market” to filter every chart.</p>
        <span className="sr-only" role="status" aria-live="polite">{announce}</span>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        <KpiCard label="Usage revenue · 12 mo" value={usd(s.revenue)} sub={market === "ALL" ? `${s.events.toLocaleString("en-US")} rated events` : `${pct(s.revenue / all.revenue)} of total`} tone="accent" />
        <KpiCard label="Monthly ARPU" value={`$${s.arpuMonthlyMean.toFixed(2)}`} sub="mean of monthly ARPU per active caller" />
        <KpiCard label="Active callers" value={last.activeCallers.toLocaleString("en-US")} sub={`${monthLabel(last.month)} · ${first.activeCallers.toLocaleString("en-US")} in ${monthLabel(first.month)}`} />
        <KpiCard label="Churned in year" value={s.churned.toLocaleString("en-US")} sub={`${pct(s.churned / s.subscribers, 1)} of ${s.subscribers.toLocaleString("en-US")} subscribers`} tone="danger" />
        <KpiCard label="Roaming events" value={pct(s.roamingShare, 1)} sub="no roaming surcharge in the dbt pricing" />
      </div>

      <div className="grid gap-5 xl:grid-cols-2">
        <ChartCard
          id="tel-revenue-month"
          title="Monthly usage revenue"
          subtitle={`Rated with sl_revenue_event's prices · ${scopeLabel}`}
          provenance={PROV}
          takeaway={
            peak.month.endsWith("-12") ? (
              <>Peak in {monthLabel(peak.month)} ({usd(peak.revenue)}) — the scenario's holiday lift; outside it, data growth lifts revenue {pct(s.monthly[s.monthly.length - 1].revenue / s.monthly[0].revenue - 1)} from first month to last.</>
            ) : (
              <>Peak in {monthLabel(peak.month)} ({usd(peak.revenue)}); revenue moves {pct(s.monthly[s.monthly.length - 1].revenue / s.monthly[0].revenue - 1)} from first month to last as data usage grows.</>
            )
          }
          table={{ caption: "Monthly usage revenue", columns: ["Month", "Revenue (USD)", "Active callers", "Events"], rows: s.monthly.map((r) => [r.month, r.revenue.toFixed(2), r.activeCallers, r.events]) }}
          height={240}
          renderChart={(h) => <EChart buildOption={revenueByMonth} height={h} ariaLabel={`Monthly usage revenue for ${scopeLabel}, peaking in ${monthLabel(peak.month)}.`} />}
        />
        <ChartCard
          id="tel-arpu"
          title="ARPU per active caller"
          subtitle="Same definition as arpu_monthly; the dashed line is the KPI above"
          provenance={PROV}
          takeaway={<>One ARPU definition everywhere: the KPI is the mean of this line (${s.arpuMonthlyMean.toFixed(2)}), not a separate annual figure.</>}
          table={{ caption: "Monthly ARPU", columns: ["Month", "ARPU (USD)", "Active callers"], rows: s.monthly.map((r) => [r.month, r.arpu.toFixed(2), r.activeCallers]) }}
          height={240}
          renderChart={(h) => <EChart buildOption={arpuByMonth} height={h} ariaLabel={`Monthly ARPU per active caller for ${scopeLabel}; 12-month mean $${s.arpuMonthlyMean.toFixed(2)}.`} />}
        />
        <ChartCard
          id="tel-market"
          title="Revenue by market"
          subtitle="Click a bar to filter the dashboard; click again to clear"
          provenance={PROV}
          takeaway={<>{marketRank[0]} leads with {pct(data.scopes[marketRank[0]].revenue / all.revenue)} of revenue, but per subscriber {perHeadRank[0]} earns most ({usd(perHead(perHeadRank[0]))} vs {usd(perHead(perHeadRank[perHeadRank.length - 1]))} in {perHeadRank[perHeadRank.length - 1]}) — size and value rank differently.</>}
          table={{ caption: "Revenue by market", columns: ["Market", "Revenue (USD)", "Subscribers", "Revenue / subscriber", "Churned"], rows: data.markets.map((m) => [m, data.scopes[m].revenue.toFixed(2), data.scopes[m].subscribers, perHead(m).toFixed(2), data.scopes[m].churned]) }}
          height={240}
          renderChart={(h) => (
            <EChart
              buildOption={byMarket}
              height={h}
              ariaLabel="Horizontal bars of 12-month revenue by market; activate a bar to filter."
              onEvents={{ click: (p: { name?: string }) => p.name && choose(p.name) }}
            />
          )}
        />
        <ChartCard
          id="tel-mix"
          title="Where revenue comes from"
          subtitle="Share of events vs share of revenue, by call type"
          provenance={PROV}
          takeaway={<>Data is {pct(dataEvShare)} of events but {pct(dataRevShare)} of revenue — at $0.02/MB the average session ({usd(s.revenueByType.DATA / s.countByType.DATA)}) is worth ~{Math.round(s.revenueByType.DATA / s.countByType.DATA / 0.01)}× an SMS.</>}
          table={{ caption: "Call-type mix", columns: ["Type", "Events", "Revenue (USD)"], rows: TYPES.map((k) => [k, s.countByType[k], s.revenueByType[k].toFixed(2)]) }}
          height={240}
          renderChart={(h) => <EChart buildOption={mix} height={h} ariaLabel={`Data is ${pct(dataEvShare)} of events and ${pct(dataRevShare)} of revenue.`} />}
        />
        <ChartCard
          id="tel-heatmap"
          title="When the network is busy"
          subtitle={`Events by weekday and hour (UTC) · ${scopeLabel}`}
          provenance={PROV}
          takeaway={<>Busiest at {String(busyHour).padStart(2, "0")}:00, quietest at {String(quietHour).padStart(2, "0")}:00; Sundays run {pct(1 - sunVsWk)} below a weekday — the capacity window for batch jobs.</>}
          table={{ caption: "Events by weekday and hour", columns: ["Day", ...Array.from({ length: 24 }, (_, h) => `${h}h`)], rows: s.heatmap.map((row, d) => [DAYS[d], ...row]) }}
          height={300}
          renderChart={(h) => <EChart buildOption={heat} height={h} ariaLabel={`Heatmap of events by weekday and hour; busiest hour ${busyHour}:00.`} />}
        />
        <ChartCard
          id="tel-churn"
          title="Churn risk by plan (last 30 days)"
          subtitle="churn_signals thresholds: ≤1 event high, ≤5 medium, else low"
          provenance={PROV}
          takeaway={<>{risk.high} subscribers flag high but only {risk.medium} medium: absolute thresholds catch accounts once they're nearly silent. Prepaid is worst ({pct(prepaidHigh)} high); a drop vs each account's own baseline would warn sooner.</>}
          table={{ caption: "Churn risk by plan", columns: ["Plan", "High", "Medium", "Low"], rows: data.plans.map((p) => [p, s.churnRiskByPlan[p].high, s.churnRiskByPlan[p].medium, s.churnRiskByPlan[p].low]) }}
          height={300}
          renderChart={(h) => <EChart buildOption={churn} height={h} ariaLabel={`Stacked bars of churn risk by plan: ${risk.high} high, ${risk.medium} medium, ${risk.low} low.`} />}
        />
      </div>
    </div>
  );
}
